export default {
  theme: {
    extend: {
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--color-theme-text-color)',
            '--tw-prose-headings': 'var(--color-theme-text-color)',
            '--tw-prose-lead': 'var(--color-theme-text-color)',
            '--tw-prose-links': 'var(--color-teal-500)',
            '--tw-prose-bold': 'var(--color-theme-text-color)',
            '--tw-prose-counters': 'var(--color-theme-text-color)',
            '--tw-prose-bullets': 'var(--color-fuchsia-500)',
            '--tw-prose-hr': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-quotes': 'var(--color-theme-text-color)',
            '--tw-prose-quote-borders': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-captions': 'var(--color-theme-text-color)',
            '--tw-prose-code': 'var(--color-theme-text-color)',
            '--tw-prose-pre-code': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-pre-bg': 'var(--color-theme-text-color)',
            '--tw-prose-th-borders': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-td-borders': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-invert-body': 'white',
            '--tw-prose-invert-headings': 'white',
            '--tw-prose-invert-lead': 'white',
            '--tw-prose-invert-links': 'var(--color-teal-200)',
            '--tw-prose-invert-bold': 'white',
            '--tw-prose-invert-counters': 'var(bg-theme-bg-color-shaded)',
            '--tw-prose-invert-bullets': 'var(--color-fuchsia-200)',
            '--tw-prose-invert-hr': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-invert-quotes': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-invert-quote-borders': 'var(--color-theme-text-color)',
            '--tw-prose-invert-captions': 'var(--color-theme-accent-color)',
            '--tw-prose-invert-code': 'white',
            '--tw-prose-invert-pre-code': 'var(--color-theme-bg-color-shaded)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--color-theme-text-color)',
            '--tw-prose-invert-td-borders': 'var(--color-theme-text-color)',
          },
        },
      },
    },
  },
}
